# Generated by Django 4.0.4 on 2022-05-30 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_road_user', '0002_user_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='create_roadUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('aadhar_number', models.CharField(error_messages={'unique': '*Aadhar Number is already exists.'}, max_length=100, unique=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default=False, max_length=100)),
                ('mobile_number', models.IntegerField(error_messages={'unique': '*Phone Number is already exists.'}, unique=True)),
                ('email', models.EmailField(error_messages={'unique': '*Email Id is already taken.'}, max_length=254, unique=True)),
                ('license_number', models.CharField(error_messages={'unique': '*License Number Is already exists.'}, max_length=100, unique=True)),
                ('profile', models.ImageField(default='profile.png', upload_to='media/')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'add_road_user',
            },
        ),
    ]
