# Generated by Django 4.0.4 on 2022-06-02 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_road_user', '0003_create_roaduser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'unique': '*Email Id is already taken.'}, max_length=254, unique=True),
        ),
    ]
