# Generated by Django 4.0.4 on 2022-06-02 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_road_user', '0005_alter_user_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create_roaduser',
            name='mobile_number',
            field=models.CharField(error_messages={'unique': '*Phone Number is already exists.'}, max_length=12, unique=True),
        ),
    ]
