# Generated by Django 4.0.4 on 2022-06-03 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_road_user', '0009_crime_crime_refrence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crime',
            name='crime_refrence',
            field=models.IntegerField(null=True),
        ),
    ]
