# Generated by Django 4.0.4 on 2022-06-03 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('add_road_user', '0011_challan_rename_crime_refrence_crime_challan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='challan',
            old_name='crime_refrence',
            new_name='refrence',
        ),
        migrations.AlterField(
            model_name='crime',
            name='challan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='add_road_user.challan'),
        ),
    ]
