# Generated by Django 4.0.4 on 2022-06-03 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_road_user', '0012_rename_crime_refrence_challan_refrence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='challan',
            name='total_penalty',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
