# Generated by Django 4.0.4 on 2022-06-03 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('add_road_user', '0013_challan_total_penalty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crime',
            name='offender',
        ),
        migrations.AddField(
            model_name='challan',
            name='offender',
            field=models.ForeignKey(default=55, on_delete=django.db.models.deletion.CASCADE, to='add_road_user.create_roaduser'),
            preserve_default=False,
        ),
    ]
