# Generated by Django 4.0.4 on 2022-06-03 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_road_user', '0014_remove_crime_offender_challan_offender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crime',
            name='vehicle_number',
        ),
        migrations.AddField(
            model_name='challan',
            name='vehicle_number',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
