# Generated by Django 4.0.4 on 2022-06-04 04:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('add_road_user', '0015_remove_crime_vehicle_number_challan_vehicle_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crime',
            name='payment_status',
        ),
        migrations.AddField(
            model_name='challan',
            name='officer',
            field=models.ForeignKey(default=20, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='challan',
            name='payment_status',
            field=models.BooleanField(default=False),
        ),
    ]
