# Generated by Django 4.0.4 on 2022-06-04 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_road_user', '0016_remove_crime_payment_status_challan_officer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challan',
            name='refrence',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
